routes:
    - name: home
      url: /
      controller: core
      action: home

    - name: hello
      url: /hello/([a-z]+)
      controller: regex
      action: hello
      parameters:
        - name

