routes:
    - name: home
      url: /
      controller: simple
      action: home

    - name: hello
      url: /hello/([A-Za-z]+)
      controller: morecomplex
      action: hello
      parameters:
        - name

